### ISSUE TITLE
Get Variables

### ISSUE THREAD

**Issue by Joey4420** [sqone2/PSFive9Admin#2]
So unlike several other options where you do not have to specify a name, when using Get Variable it returns an error.

Get-Five9CallVariable
Cannot find a Call Variable with name: "" within the Group "". Remember that Name and Group are case sensitive.
At C:\Program Files\WindowsPowerShell\Modules\PSFive9Admin\1.0.62\Public\CallVariables\Get-Five9CallVariable.ps1:41 char:13
+             throw "Cannot find a Call Variable with name: ""$Name"" w ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot find a C...case sensitive.:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot find a Call Variable with name: "" within the Group "". Remember that Name and Group are case sensiti 
   ve.

**Comment by sqone2** [comment]
Thanks Joey! I just made a change that makes the `-Name` and `-Group` parameters mandatory so that you can't use the function without them being specified. In order to see all variables and groups with one command, you can use `Get-Five9CallVariableGroup` with no parameters
