### ISSUE TITLE
Duplicates 

### ISSUE THREAD

**Issue by kabellaaac** [sqone2/PSFive9Admin#4]
Hi, I was just wondering if there was a way to easily duplicate a skill, campaign, etc? Cause I have templates made, and all I need to do is duplicate it and then rename them. 
Thank you so much

**Comment by sqone2** [comment]
Hey @kabellaaac, unfortunately although duplicating is easy in the Five9 GUI, there's not an easy way to duplicate using the API. The only function that I built which allows for it is `New-Five9User` which allows you to specify a user to copy roles from. i.e. `New-Five9User -CopyRolesFromUsername 'templateUser@domain.com'`
