### ISSUE TITLE
Setting password via module command does not unlock account.

### ISSUE THREAD

**Issue by SunsparcSolaris** [sqone2/PSFive9Admin#5]
I've tested this a few times with the same result each time. Password is changed but checking the Five9 Admin portal shows the user is still locked out. I checked the Five9 API documentation but didn't see any entries for removing a lock.

Is it possible to do this in the module at all? I would like to use it for password resets where users are locked out in addition.

**Comment by sqone2** [comment]
Hello, unfortunately this is a limitation of the Five9 API that the Powershell module leverages. Please submit this to Five9 as a feature request.

Thanks!
